language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mmushyk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mmushyk/docker-react npm run test